spring:
  application:
    name: 'Online Food Ordering '

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: hello
    url: jdbc:mysql://localhost:3306/food_ordering_app
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    
    
server:
  error:
    whitelabel:
      enabled: false

    